#!/bin/bash

# Set the URL for Pikachu's data
URL="https://pokeapi.co/api/v2/pokemon/pikachu"

# Set output and error file names
OUTPUT_FILE="data.json"
ERROR_FILE="errors.txt"

# Make the API request using curl
curl -s -f "$URL" -o "$OUTPUT_FILE"

# Check the exit status of curl
if [ $? -ne 0 ]; then
    echo "[$(date)] Failed to fetch data from $URL" >> "$ERROR_FILE"
fi

